# Generated by Django 6.0.2 on 2026-04-21 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_availabilityschedule_effective_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='gender',
        ),
    ]
